In [1]:
import numpy as np

In [25]:
# Задание 1
N = 10
np.arange(N, 0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [28]:
# Задание 2
# Диагональная матрица
np.diag(np.arange(N,1,-1))



array([[10,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2]])

In [27]:
# Сумма значений
sum ( sum(x for x in np.diag(np.arange(N,1,-1)) ))


54

In [ ]:
# Задание 3

In [21]:
from numpy import linalg

In [22]:
a = np.array( [ [4, 2,1], [1,3,0],[0,5,4] ] )

In [23]:
b = np.array( [4, 12,-3] )

In [24]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])